### ISSUE TITLE
Question about ordering of receiving data change

### ISSUE THREAD

**Issue by startemplar** [Azure/iot-gateway-opc-ua#11]
I have 2 questions:
1. In OPC UA, can client retrieve multiple variable values at the same time?
2. If I use the monitoredItem approach, is it safe to assume that older variable value will always be published to broker earlier than later variable values?
Thank you.

**Comment by barnstee** [comment]
These are generic OPC UA questions and have nothing to do with the gateway module. Please read up on how OPC UA work in general: Visit http://opcfoundation.github.io/UA-.NETStandardLibrary/ for OPC UA documentation.
