### ISSUE TITLE
Provide more documentation about OPC UA and azure connection

### ISSUE THREAD

**Issue by tejasklodha** [Azure/iot-gateway-opc-ua#14]
Dear Sir,

If I have OPC UA server then how can I use this "iot-gateway-opc-ua" and update live data to azure?
Provide Example.

Thanks,

**Comment by barnstee** [comment]
Please see here for the Azure-hosted other end of the solution:
https://github.com/OPCFoundation/UA-.NETStandardLibrary/tree/master/OpcUaWebTelemetry

**Comment by Norman03** [comment]
Above link not working @barnstee
