### ISSUE TITLE
Cannot load Opc.Ua.Client.SampleModule.Endpoints.xml

### ISSUE THREAD

**Issue by 606simps** [Azure/iot-gateway-opc-ua#2]
Hi,
I can compile and run the sample with no errors. Except one thing that the client cannot connect to the server. I traced the code and found the client were not able to load cached endpoints.

```c
ConfiguredEndpointCollection endpoints = m_configuration.LoadCachedEndpoints(true);
```

I always get count 0 even I have specified endpoints in the xml file.
Do I have to put "Opc.Ua.Client.SampleModule.Endpoints.xml" somewhere specific?
Or anything wrong with my xml?

[Opc.Ua.Client.SampleModule.Endpoints.txt](https://github.com/Azure/iot-gateway-opc-ua/files/610468/Opc.Ua.Client.SampleModule.Endpoints.txt)

File extension is changed to txt for uploading, it is Opc.Ua.Client.SampleModule.Endpoints.xml on my machine.

Thanks,
Stephen

**Comment by barnstee** [comment]
Your file works for me. If the endpoints XML needs to be in your gateway exe directory, along with all the other configuration files.
