### ISSUE TITLE
Building OPC UA client with .NET

### ISSUE THREAD

**Issue by maccence** [Azure/iot-gateway-opc-ua#21]
I Downloaded the code from https://github.com/Azure/iot-gateway-opc-ua and I found  in the lib folder a bloc note asking me to add these files to build the project: 
aziotsharedutil.lib
gateway.lib
nanomsg.lib
parson.lib

But I can't find them on the net.

I tried to do this by enable dotnet binding using these two commands:
build_dotnet.cmd
build.cmd --enable-dotnet-binding
But the result of the first command was : "wget is recognized as the name of a cmdlet, function or..."

See below some pictures illustrating my problems.

Can someone help me? Thank you.
![2017-03-08 10_54_57-new issue azure_iot-gateway-opc-ua](https://cloud.githubusercontent.com/assets/26273323/23699047/0e9a9898-03ee-11e7-8d81-f5b1a116b6e8.png)
![2017-03-08 10_55_33-new issue azure_iot-gateway-opc-ua](https://cloud.githubusercontent.com/assets/26273323/23699060/1c0739f0-03ee-11e7-9d7a-69cb7213eec8.png)

**Comment by 606simps** [comment]
Looks like you will also need to clone a copy of IoT Gateway SDK and get the libs from it.
Refer to the last paragraph of [this](https://github.com/Azure/iot-gateway-opc-ua#running-the-module).

**Comment by barnstee** [comment]
Yeah! This pain will go away soon as we're working on creating NuGet packages for all of this.
