### ISSUE TITLE
Opc Ua Publisher module configuration

### ISSUE THREAD

**Issue by janfl** [Azure/iot-gateway-opc-ua#25]
I have resent downloaded the opc au module again because i want to run with the latest version.

But i'm wondering how i can connect the same module to 2 different OPC Servers? In the old version we had an subscription config sections that could support this....

We also had the possibility to add device id and sharedaccesskey in the subscription but this has gone aswell is this type of device access method not supported anymore?

Last but not least why is publishednodes not part of the module configuration?

**Comment by barnstee** [comment]
> But i'm wondering how i can connect the same module to 2 different OPC Servers? In the old version we had an subscription config sections that could support this....
This is described in the "Configuring the Module" section of the readme. You can connect to as many servers as you like.

>We also had the possibility to add device id and sharedaccesskey in the subscription but this has gone aswell is this type of device access method not supported anymore?
We have automated this and hard-coding the sharedaccesskey is no longer necessary (this was a security risk!). Now, you can run the gateway with the owner connection string ONCE and the GW auto-registers with IoT Hub.

>Last but not least why is publishednodes not part of the module configuration?
The publishednodes file is auto-generated as soon as you use the new server interface and publish a node. You can of course also generate the file yourself as described in the "Configuring the Module" section.
