### ISSUE TITLE
Create session failed

### ISSUE THREAD

**Issue by radezheng** [Azure/iot-gateway-opc-ua#27]
Hi,
I am trying to build the opc ua gateway with our partner,  who has their own OPC UA Server box. we managed to build the code, but when trying to connect to the UA server, we got time out error, can you help? thank you!
![error 1](https://cloud.githubusercontent.com/assets/12248649/25667674/c88af970-3056-11e7-8166-1b132b953d2e.png)

**Comment by barnstee** [comment]
You timed out trying to connect to the server "BadRequestTimeout". Can you try to reach the server with an OPC UA client first to make sure it is accessible?

**Comment by barnstee** [comment]
do you still have this issue?
