### ISSUE TITLE
[Suggestion] create tags corresponding to iot gateway sdk

### ISSUE THREAD

**Issue by 606simps** [Azure/iot-gateway-opc-ua#3]
Can we have tags that are verified with certain stable versions of iot gateway sdk. For example, I may want to use "2016-11-18" to download both gateway and opc client module. 
Thanks!

**Comment by barnstee** [comment]
Good idea...

**Comment by barnstee** [comment]
Done!

**Comment by 606simps** [comment]
@barnstee I didn't see the tags yet. Did you create them locally or on Github? You can find it under the release tab. Thanks.

**Comment by barnstee** [comment]
My bad. Fixed.
