### ISSUE TITLE
Stupid question?

### ISSUE THREAD

**Issue by gillerman** [Azure/iot-gateway-opc-ua#4]
After cloning Azure/azure-iot-gateway-sdk and Azure/iot-gateway-opc-ua to a fresh machine:

I try to build the binding sample I get the following errors:

Severity	Code	Description	Project	File	Line	Suppression State
Error (active)		cannot open source file "stdio.h"	dotnet_binding_sample	c:\Users\John\Documents\Visual Studio 2015\Projects\iot-gateway-opc-ua\binding\main.c	4	

Severity	Code	Description	Project	File	Line	Suppression State
Error (active)		cannot open source file "stddef.h"	dotnet_binding_sample	c:\Users\John\Documents\Visual Studio 2015\Projects\iot-gateway-opc-ua\inc\azure_c_shared_utility\buffer_.h	12	

After adding C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include to my include path, I get:

Severity	Code	Description	Project	File	Line	Suppression State
Error	C1083	Cannot open include file: 'corecrt.h': No such file or directory	dotnet_binding_sample	C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\crtdefs.h	10	

After adding C:\Program Files (x86)\Windows Kits\10\Include\10.0.10150.0\ucrt to my include path, I get:

Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK1104	cannot open file '..\lib\gateway.lib'	dotnet_binding_sample	C:\Users\John\Documents\Visual Studio 2015\Projects\iot-gateway-opc-ua\binding\LINK	1	

The issue is that the the project Microsoft.Azure.IoT.Gateway only builds Microsoft.Azure.IoT.Gateway.dll and not gateway.lib.  The line in the build instructions seems incomplete as these libs are don't seem to be built when building the dotnet binding project: 

"Once done, copy the just compiled aziotsharedutil.lib & .pdb, gateway.lib & .pdb, nanomsg.lib & .pdb and parson.lib & .pdb to the /lib folder. It is easiest just to search for them. If you find multiple copies, any of them will do."

**Comment by barnstee** [comment]
The only stupid question is the one that didn't get asked. :-)
You are right, the dotnet binding project only builds the managed Microsoft.Azure.IoT.Gateway.dll. You need to build the entire SDK (the C libraries) using the build command in tools and don't forget to enable the dot net language binding. Just do a build /? and you'll find it. You also seem to be missing standard C libraries and headers from your VS path. Do you have everything set up correclt yin VS, e.g. does another C++ console app or something like that build OK?

**Comment by barnstee** [comment]
@gillerman, is your issue resolved? Then please close...

**Comment by gillerman** [comment]
Complete
