### ISSUE TITLE
release corresponding to GW SDK 2016-12-16

### ISSUE THREAD

**Issue by 606simps** [Azure/iot-gateway-opc-ua#5]
Hi,
I have tested that the latest Opc Ua module works just fine with GW SDK 2016-12-16. Would you make a corresponding release of the module?

Thanks,
Stephen

**Comment by barnstee** [comment]
Got one better for you: I'm automating the build completely and decoupling the module from the SDK via a NuGet package. No more copying around of headers or libs! I've built a NuGet package for the 2017.1.13 release of the SDK and I'm about to check it in. Now, as new SDK releases come out (and corresponding NuGet packages), you can simply upgrade the package.
