### ISSUE TITLE
Code is not loading the "dotnet" module

### ISSUE THREAD

**Issue by terrymandin** [Azure/iot-gateway-opc-ua#7]
I have compiled the azure gateway sdk and moved the related lib, pdb, and dlls to the appropriate directories (lib and binding) as per the build instructions.  When I run the code it is failing to load the "dotnet" module on line 331 of  module_loader.c.  It is returning "NULL".  I have confirmed that the dotnet.dll is being copied from binding to bin\debug.

**Comment by barnstee** [comment]
You'll need to debug it. Probably a typo in the gateway config file...

**Comment by barnstee** [comment]
Closing, LMK if you still have an issue.
