### ISSUE TITLE
Error when find the right session and endpoint URI using lookup

### ISSUE THREAD

**Issue by sumongithub** [Azure/iot-gateway-opc-ua#8]
Hi,
File: Module.cs
Line# 165

I have configured end point e.g. opc.tcp://LocalHost:45678 in configuration file. When execute the application found error message -
 "Opc.Ua.Client.SampleModule: ERROR: Could not find endpoint URL opc.tcp://LocalHost:45678 in active server sessions, NodeID i=2258 NOT published!"

During debugging understand code "session.Endpoint.EndpointUrl" returns string "opc.tcp://LocalHost:45678" but code "Utils.ReplaceLocalhost(nodeLookup.EndPointURL.ToString()" returns "opc.tcp://localhost:45678/". Hence string comparison condition was not satisfied. 

Modification of code from "session.Endpoint.EndpointUrl" to "session.Endpoint.EndpointUrl.ToLower().ToString() + "/"" resolves the problem and working fine.

Thanks & Regards,
Sumon

**Comment by barnstee** [comment]
Thanks for the report, fixed in https://github.com/Azure/iot-gateway-opc-ua/pull/9
